name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 10 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: | 
          sudo apt-get -qq update
          sudo apt-get -qq install rake bison git gperf
      - name: Clone mruby
        run: git clone https://github.com/mruby/mruby.git
      - name: Copy build file
        run: cp -fp ./.github_actions_build_config.rb ./mruby/build_config/github_action.rb
      - name: Test
        run: |
          cd mruby
          rake MRUBY_CONFIG=github_action
